# Vim-like shortcuts
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Window navigation
bind -r C-h previous-window
bind -r C-l next-window

# Custom clear behavior
bind-key -n C-l send-keys C-l \; run 'sleep 0.2' \; clear-history

# Pipes the default copy-mode-vi 'y' selection to xclip so it also lands
# in the system clipboard, not just tmux's internal paste buffer.
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Declare your plugins here:
set -g @plugin 'dracula/tmux'
set -g @plugin 'JosephLai241/tmux-line-numbers'

# Dracula - Custom Settings
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon "#S"
set -g @dracula-show-location false
set -g @dracula-cpu-usage-label " "
set -g @dracula-ram-usage-label " "
set -g @dracula-battery-label false
set -g @dracula-show-battery-status true
set -g @dracula-plugins "battery ram-usage cpu-usage"

set -g @dracula-colors "
# simple gruvbox Color Pallette
white='#EBDBB2'
gray='#32302F'
dark_gray='#282828'
light_purple='#B16286'
dark_purple='#504945'
cyan='#689D6A'
green='#98971A'
orange='#D65D0E'
red='#CC241D'
pink='#D3869B'
yellow='#D79921'
"

# General - Custom Settings
set -g status-position top

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
